### ISSUE TITLE
Process requirement exceeds available memory when running 'make mmi index'

### ISSUE THREAD

**Issue by MasterLH64** [epi2me-labs/wf-aav-qc#12]
Hi，

I am trying to run wf-aav-qc demo data with a laptop workstation. Process worked fine until the pipeline:make_mmi_index, which showed the following error,
ERROR Error excuting process > pipeline:make_mmi_index
Caused by:
Process requirment exceeds available memory -- req : 16GB; avail: 15.3GB

I have tried using custom config (-c config.cfg, setting memory to 8GB), but it didn't work. 
Is there a way I can get the process running on the current computer?
Thank you!

**Comment by nrhorner** [comment]
Hi @MasterLH64 could you share the contents of config.cfg?

**Comment by MasterLH64** [comment]
Hi Neil,

The content is as follows, according to https://labs.epi2me.io/wfquickstart/

executor {
    $local {
        cpus = 4
        memory = "8 GB"
    }
}


After applying the .cfg, it showed a different error:

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: null.

The full error message was:

Error executing process > 'pipeline:make_mmi_index'

Caused by:
  Process requirement exceeds available memory -- req: 16 GB; avail: 8 GB


Command executed:

  minimap2 -t 4 -I 16G -d genome_index.mmi ref_genome.fasta

Command exit status:
  -

Command output:
  (empty)


The nextflow command is 
nextflow run epi2me-labs/wf-aav-qc --fastq simulated_reads.fq --itr1_end 156 --itr1_start 11 --itr2_end 2286 --itr2_start 2156 --ref_helper helper.fasta --ref_host cell_line.fasta.gz --ref_rep_cap repcap.fasta --ref_transgene_plasmid transgene.fasta --override_basecaller_cfg dna_r10.4.1_e8.2_400bps_sup@v5.0.0 -c my_config.cfg

**Comment by MasterLH64** [comment]
Hi @nrhorner , do you have any updates on this question ?

**Comment by MasterLH64** [comment]
Problem solved.
