### ISSUE TITLE
Please support ARM

### ISSUE THREAD

**Issue by enc-wmatern** [epi2me-labs/wf-aav-qc#8]
### Is your feature related to a problem?

```
[11/892404] Submitted process > pipeline:getVersions
ERROR ~ Error executing process > 'pipeline:make_index'
Caused by:
  Process `pipeline:make_index` terminated with an error exit status (137)
Command executed:
  minimap2 -t 4 -I 16G -d genome_index.mmi ref_genome.fasta
Command exit status:
  137
Command output:
  (empty)
Command error:
  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  .command.sh: line 2:    67 Killed                  minimap2 -t 4 -I 16G -d genome_index.mmi ref_genome.fasta
```

### Describe the solution you'd like

Support for ARM. New Apple laptops use ARM.

Maybe you could utilize docker's emulation layer?: https://stackoverflow.com/questions/70872114/x86-docker-image-on-arm

### Describe alternatives you've considered

Spinning up an EC2 instance to run this - but then I can't use the nice EPI2ME interface.

**Comment by nrhorner** [comment]
Hi @enc-wmatern 
The reason the workflow dies was because it used too much memory at the at the `make_index` step. How much RAM doe you have available on your machine?

**Comment by enc-wmatern** [comment]
Ah I see. I have 32GB of memory (which should be plenty). But I looked at my setup for Docker Desktop - Settings / Resources and saw that resources were constrained to 8GB. Extending this to 32GB allowed me to run the pipeline with the same input settings as the above. Thank you!

Small thing: I noticed in the README: "ARM processor support: False" - I assume this is no longer true?

**Comment by nrhorner** [comment]
@enc-wmatern Great. Thanks for letting me know.  

Currently for this workflow, there isn't an ARM container, so it's not supported.
